name: Action Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/**"

jobs:
  action-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5

      - name: Run action lint
        run: go run github.com/rhysd/actionlint/cmd/actionlint@latest
