name: Analysis CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - analysis/**
      - .github/workflows/analysis-ci.yaml
  pull_request:
    branches:
      - main
    paths:
      - analysis/**
      - .github/workflows/analysis-ci.yaml

jobs:
  analysis-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.12"

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.14
          enable-cache: true
          cache-local-path: ~/.cache/uv
          cache-dependency-glob: analysis/pyproject.toml

      - name: Install package
        id: install
        working-directory: analysis
        run: uv sync --all-extras --dev

      - name: Run ruff
        shell: bash
        working-directory: analysis
        run: |
          uv run ruff check .
          uv run ruff format . --check

      - name: Run mypy
        shell: bash
        working-directory: analysis
        run: |
          uv run mypy src --config pyproject.toml
        if: (success() || failure()) && steps.install.outcome == 'success'

      - name: Run pytest
        shell: bash
        working-directory: analysis
        run: |
          uv run pytest tests
        if: (success() || failure()) && steps.install.outcome == 'success'
