name: Frontend CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**"
      - .github/workflows/frontend-ci.yaml
  pull_request:
    branches:
      - main
    paths:
      - "**"
      - .github/workflows/frontend-ci.yaml

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      checks: write
      contents: write
      issues: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: package.json

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install package
        run: pnpm install

      - name: Run eslint
        run: pnpm lint

      - name: Run danger
        run: pnpm danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
